module.exports = {
  mongoStore: require('connect-mongo'),
  cors: require('cors'),
  dotenv: require('dotenv'),
  express: require('express'),
  sessions: require('express-session'),
  httpStatus: require('http-status-codes'),
  mongoose: require('mongoose'),
  morgan: require('morgan'),
  passport: require('passport'),
  LocalStrategy: require('passport-local'),
  passportLocalMongoose: require('passport-local-mongoose'),
  path: require('path'),
  rfs: require('rotating-file-stream'),
  winston: require('winston'),
  wrfs: require('winston-daily-rotate-file'),
};
